channels:
- conda-forge
dependencies:
- python==3.11.9
- pip
- numpy==1.23.5
- dill
- matplotlib
- pandas
- scipy
- sortedcontainers
- spyder
- statsmodels
- pip:
  - --editable=git+https://github.com/stavis1/DE_analysis_optimizer.git#egg=DE_analysis_optimizer
